### PR TITLE
[JENKINS-38465] it now search credentials also into folders

### PR DESCRIPTION
**Pull request by kuisathaverat**
@reviewbybees 

https://issues.jenkins-ci.org/browse/JENKINS-38465

### CODE REVIEW

**Comment by joxford-soltech** [comment]
Any update on this? I've been wanting to use this plugin but it has broken our credentials plugin.

**Comment by recampbell** [comment]
@reviewbybees done

**Comment by kuisathaverat** [comment]
@ndeloof this plugins is in adoption, I have requested to be the maintainer of this plugin few days ago in the jenkins-dev group, If I was the maintainer, I could release the last changes.

**Comment by daniel-beck** [comment]
@kuisathaverat Done!

**Pull request merged**
